runtime: python310

handlers:
- url: /static  # Configuramos la ruta para los archivos est치ticos (CSS, JavaScript, im치genes, etc.)
  static_dir: static

- url: /.*
  script: auto  # Usamos 'auto' para que App Engine detecte autom치ticamente tu aplicaci칩n

instance_class: F4

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  min_instances: 0